apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: arungupta/helloworld-spring-boot:latest
        ports: 
        #- containerPort: 443
        #- containerPort: 80
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - name: http
    protocol: TCP
    port: 443
    targetPort: 8080
  type: ClusterIP #LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/upstream-hash-by: "$request_uri"
  name: hello-world-ingress
spec:
  rules:
  - host: hello-world.com
    http:
      paths:
      - backend:
          service:
            name: hello-world
            port:
              number: 443
        path: /
        pathType: Exact
  tls:
    - hosts:
        - hello-world.com
      secretName: selfsigned-cert-tls
      
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  #namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  #namespace: cert-manager
spec:
  dnsNames:
    - hello-world.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned