---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: simple-app
  name: simple-app
  annotations:
    flux.weave.works/tag.simple-app: "glob:latest"
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: simple-app
    spec:
      containers:
      - image: docker.io/hanken16/simple-app:latest
        name: simple-app
        resources: {}
      imagePullPolicy: Always
      imagePullSecrets:
      - name: dockerhub-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  selector:
    app: simple-app
  ports:
  - name: http
    protocol: TCP
    port: 443
    targetPort: 80
  type: ClusterIP #LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/upstream-hash-by: "$request_uri"
  name: simple-app-ingress
spec:
  rules:
  - host: hello-world.com
    http:
      paths:
      - backend:
          service:
            name: hello-world
            port:
              number: 443
        path: /
        pathType: Exact
  tls:
  - hosts:
    - simple-app.com
    secretName: selfsigned-cert-tls
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp:
  name: test-new-ns
spec: {}
status: {}
