---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: simple-app
  name: simple-app
  annotations:
    flux.weave.works/tag.simple-app: glob:stg-*
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: simple-app
    spec:
      containers:
        #public.ecr.aws/e0j8j8j7/versent-simple-app:latest
      - image: docker.io/hanken16/simple-app:stg-075f188
        name: simple-app
        resources: {}
        imagePullPolicy: Always
      imagePullSecrets:
      - name: dockerhub-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  selector:
    app: simple-app
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP #LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/upstream-hash-by: "$request_uri"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: simple-app-ingress
spec:
  rules:
  - host: simple-app.com
    http:
      paths:
      - backend:
          service:
            name: simple-app
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - simple-app.com
    secretName: selfsigned-cert-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  #namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  #namespace: cert-manager
spec:
  dnsNames:
  - simple-app.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-config
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodWIuZG9ja2VyLmlvIjp7ImF1dGgiOiJhR0Z1YTJWdU1UWTZjWGRsTVRJelFWTkVJVUFqQ2c9PSJ9fX0K
    #ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fSwKCQkicHVibGljLmVjci5hd3MiOiB7CgkJCSJhdXRoIjogIlFWZFRPbVY1U25kWldHeHpZakpHYTBscWIybFpWekZVVkd4VmQxWllhekZpUkdSUFlUSkdiVnBFVVhka1NHTnlWRVJDYVdNeVpEVldiVkpDVVd4T2RFOVZNRFJhVjFJd1YwUktkazlXVGtOamJtZHlaRmhTYUU1dFRUTlVWM1F6WkRJNGVHUnJOSGhsUm1ReFQxWnNNMUZWU1hwTk1scFNWak5GTTFkVlRscFNWVnBPWVZSRmVtUnRhR2xrTWpseVZXdDBiMk15T1d4VmEyUXpWVWhTYzB3emJFUlBWbXgwWWtSUk1WZFdXbTFqTWpGd1QxaE9UVnBFVmxsT1IzaFpWMVYwUzBzemFFcFZWMHB4V2taT1lWRXhWbTVaVlc4d1dYazVVbFpyYkVOVE1WSk9XbnBrV1U5SVZsZFJhbGwyUzNsMFFsWXhZelJUYWxaYVMzcHNlazVHWjNoVlZ6RnlUbTEzY2sxVVpHMWthMmhVVVZad2QwNXRWalpQVjJkNFlsWnNlVlpwZEVOU1NIQkhWVEpzVldWdGFEQmpWRWswVkhwak5WSllhRkZrTVd4VlRVUlNhVmRJVm5kT01ERk9Ua2hrZUdGcmNEUmtWR3N3VFVWTk1HUXlPWGRQUmtwaFkzcG9XRlV6UVRKalJ6Rk5VbXhaY21WRVJqRlBWM2g2VmpOYWNGZEdTa0pTUjNCcVVqRndjV0pHU2paWmJGcDNWWHBaTlZkcE9XeFRSMDE1VW1zNVJtRlVVbE5oUXpsM1lrUmFlV0V5Y0VKUFJURnFZVEphU1dWRlJYSmtNVkpFVjFSR2IxUXdOVkJhVjBwMVRWYzViV0pVVGtSVWFsSjRVbXhDZWtzd2FGWmFibEozVGtoa1RXSllRbTlOTVVFeVZqTldjRlF6V2xGaWJHUnZUa1JPZW1JeVVYcFRTRUY1VG10Rk0yRnJiM2RoTWxsNVpETlNSMkZ0T1ZwV01sVjVVbFZhUkZkRlZsSlRibEpZWTBSU2NsVlZNVmxOZWxKb1QxWldXRlpHWkc1Tk1sVjRTekZvYkdWRmRFTmpSMnh3VWtNNE5HSkVUbGxSYkhCdlRrWkNOazVHU2pCU1ZXOHdZa1ZXYVZWWFZYaFVNVlpYVWxSa1UwOVhkSGxOUnpWTVQwZFNNVmw2VFRCYVZtaFdWMjB3ZG1GV2JESmlNRXBJWldrNVlWUlZXbFZOUlRGT1UyMUtSMUZyZHpKaVZtaGFWRmRvUzJKVVdqRmlNVUY0VTBaR2MxVllTa2hoUjBwWFRsWkNhMHd6U2tkalZXeERZMnRXZEZacVZucFJhMFkxVFVWa05XUkhlREJPTTJ4SlUwWkNka3d6VVRCalIyOTNWVE52Y2xaWWJFOVRiRmw0VTFobk1HSkVRa1psVkZwclRtdGtXVll6YUhkYVJ6bG9UREZDVjA1dGVGbFJNMVl6VGpOT1RHRldVbHBpV0ZKWFUwTnpNMXBUY3pKa1NGSlhWMFJXYVZscVduVmtNMGwyVmtkYWVHUXpaRmRPVld4cllWWmtXRXd5TVRCWGJWWkVUVzFTTTA1RGRGSlRSM2hSVlZkVmQxRlRkR2hpTW5neFVXeHdjbFF3WkVsTk1sSjFZbFphYTB3d05VVlBWMWt4VWxST2Ewc3dOVEJhTVVGNlZqSkpNbVJIYUZOVlYxSlNaVlJGTldWVE9XbFZSbkIzVkVWa1VrMVVaelZrUmxVelZHdFdjRTE2YUhKVE1GSnBWMnM1V0ZreWREQlBWa1ozVG0wMWRGTnRNVmhpYWtFeVlVUmpNbEl6Um1GaE1rNU1XV3QwTUUxcVp6QmlNR1F4V2pKNGFtTkhkRVZPYmxKVFlUQldlV0ZyYkVaT2VsSnRZbXBPU2xJd2JIRlBWM0JRWkd4amVFNUZUazFWTUU1dVpFZHdNVkpGVGpCUlZFcHVUbGM0ZUdOWFVqQmFiV1F5WVd0d01WUklWbE5TUnpGeVZqSlNSbVZGT1RWWmF6RklUbXRXTkdWSFNrUmliVkkxVjFWNGFGcEdXbXBSYkdRMldtMWtWbEp0Y0VSWFdGcFFVbFZyZDJGR1RtbGlNMUpxVG01b05GTnJVa1JrUldSRldUQmtjMWxVV2xGU1JWSTFaV3R3ZG1GR1JUQldiR3hFVmxWNFJVNVdiRXBVVlRWWFpXcG9WRnB0T1hwUlYwcHlUbmwwV1ZKV2FIbFpWVFZHWWpKc2Exa3dZekZpYVRsUFkxZGFNVmRVUm5OYVJFRjNUVzFTUkV3d05VeFpWRXBRWVdwR2NHRXdhRzFTUm10NFRESjRNRmxxVlRSa1NGbDNWMVpSZG1Jd1NuTk9RM1JZWkZWT2JXSnJOVVpTYm5CcFRrVndiR0V6YjNsVFIzaFJWVlpPUkU1SFdqTmlTRlpDWXpCNFQwNUhPV2xqU0ZaR1dqSldkR1F4Y0RGYWFYUkNVVzVWZUdWVWEzcFNhekY0VjFOemVWRjZWblpoVkZaR1pESTVUMDlWZUVKYU1HUlRWMnRPVDFaSFRqQlNWM1JOVVdwb1dsSlhXa1JVTW5CS1UxWkpNbVJwZEV0aE0xSlVUbXRrY1dWSVVtdFhhbXhRVmtoYVdGZFdhR2xYYmtsMlRXeEdlVmR0Y0ZkT2JXUkNZVlU1YmxveWJEUmhSRXBLVDBOMFRtSnRjRTlqYTFaRlRVZHNlRlpUT1Zkak1EVklXbTFvU1dGclZUUlBSR3h3WkZaYU5WUkdVbXBSYVRsYVZsVjNOVmxXU25sVlJYTXlaRlUxYTFOcVNteGpla1p1WWpCS2JrNVhOVVZUV0hCR1RrVktkbFV3VFRCYWJuQjVWMFZTTVdWWWJFZE9iWGd6VjBkd1lXTllSbkpXVkZwTVl6RmFXbE14UW5kU2VsWTBXVk00TldWSWJHbGlNMnhxVm14c01sTldhRk5UYVhNeVRWVTVUMDVGWjNkV2JYQklZakIwUTJOdFRYbFZVemx2VTJ0R2RtRXhTWGhVYlRWUVZqTnNTazFGWnpOTmVtaE9Vek5CZDJSVE9XeFJla1V5VWtad1UySXlaRWxhVkZaV1YwVjNNbU51VFhKWFIyOTJUMFU1V21Kc2IzZGFNMHBvVmxaR2ExSXpSbTVXTUhCd1kxTTVjVnBVVGtsU01qRlJaSGs1ZDBzd1pHOVZWMWw0VkdwSmRtUlliRVpTTW5CV1QwVnZlazR5YTNkTlIxcFNXVlpvV1UxVVJqTmFNRkpMWkRBeFlWTkdUa1JOUjAxMlRsVk9WRmRxU1RGVVYwNHdVVlJPVEdKSVZqRlZWemxYVlcxb1ZHRlVaSEJNZWxaWVYwTnplVkZVYkcxVFJYTXdWREZLU2xJelNteGpiVGx5VVhwak1tRjVPVmRhU0UweFkwVTVkMkpYUmtKUVZEQnBURU5LYTFsWVVtaGhNbFkxU1dwdmFWRldSa3BSYTBaSllWWm9NbFl3T1hGaVNFSTFZMjVKY2xKSVdrbFhibVJLWWxoV1UxTkRPREZaTURSMllVUnNNMVpIU25Oa2FsbHlaVzVuZUZNelpIQlhSa1pHWlZjNE5HTlVWa3hVYTJSNlVWUm9TV1JYY0ZWaGFYUndWa1pHU2xGVlJrSlJWMXB4VVdwb1Exb3lkSGhoUjNSd1VucHNNMDFGU2tOa01rWnVXVzV3UTJSRlJtNVNWVVpPVWpKa1NGRXhUbmhTTVU1S1dXcE9SVlZWVmtsUlZsSkNXbFZLYm1KSFpHOWhNbVJEVjJ4R1RsSlZSbFJPU0dSR1ZWWkdUbEpVU2xaUFZVa3dVMGhKZWxGVWF6TmxhMnhxVVRCR2JsSldSbTVTU0ZweFlXNXdjMk14VGxSak1IaERXbXBHY1dJd2JGRmhlbGwyVkRKYWJXVlhjRmhsYlVwUFpXeE5NbGw2VWtOU2VtaFVaRlJzUkZGNlRYWmtWM0JGVFRGV1RVNXJkSEZqTTBrell6Sm9XazlHY0VOaVF6bGFWRmRXVTFwSVozZGFNMGt3VG1zNWNWWllRa0pRVkRCcFRFTktNbHBZU25waFZ6bDFTV3B2YVUxcFNYTkpibEkxWTBkVmFVOXBTa1ZSVmxKQ1dEQjBSbGRUU1hOSmJWWTBZMGRzZVZsWVVuQmlNalJwVDJwRk1rMXFhelZQUkVWNVRVUkNPUT09IgoJCX0KCX0sCgkiY3VycmVudENvbnRleHQiOiAiZGVmYXVsdCIKfQ==
#eyJhdXRocyI6eyJodWIuZG9ja2VyLmlvIjp7ImF1dGgiOiJhR0Z1YTJWdU1UWTZjWGRsTVRJelFWTkVJVUFqQ2c9PSJ9fX0K
type: kubernetes.io/dockerconfigjson
