---
# The service account, cluster roles, and cluster role binding are
# only needed for Kubernetes with role-based access control (RBAC).
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cicd
  labels:
    name: flux
  name: flux
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: flux
  name: flux
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
  - nonResourceURLs: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: flux
  name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: cicd
---
apiVersion: v1
kind: Secret
data:
  identity: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUF3NEo3REV5WUhEK1ROS1Z4UzM0Y3pMbThmMkdQMTdkMlEzZFBNMHJybzdKZTFwamNwdmU0Cis3Y2JmdDRlRTBmQ3V4MWdHRFk3YzNQUWswc2YyQzltc3Zid1l6R1NRVFhGYU1DU3E1YU1tNHd2YnMxd2ZsYVhBVjFtYXYKVERRc3k4WmtMRWlCUlN4cWRHTmtURUhlOE5JM21vSTBDZjM2cTJ4RmFWdmhPVDY3b0xkc2FxTXZTaHdnZTlURTFGandnTQp1ZHlYYkR2TjFZcGdUakdIckI0SGdnUXprcHFCMmZkS1lDQjdkZ0RmUU4zbUtkWm1Tem96cmNrNHFOWk9zWmpOSFhvcTZKCkYwd0ZjV044aUZ4dzdJejlscXJOUWsxSTRmNWVhWkhsdU9FVkVlRFRmRGswdVErcDJRei9YdmRIVHpVSm93ZEJ6aW9vTDUKdmlGRE55dDZNOVJ6TnFXdCtoL1JFeEEvclMva0JwTGNCRjZJcXpSb3o2aDR4Z09QeGhkck84QVd3MzZPTzR6L3NxRW9tVQpZdWJoZ3ROLzloeSsvMGdXSVVYVDhnMzRnSVpFd2lzaDZFMENsM0tSY0R4Uy9NeDBzWlRFVE9iREY2L01NamlCSWEwUUxWClVmUDNBbThLd09wYm1FdnIxeXJCZnVmTGphNWpDbzFRQXFrSjBFY2pBQUFGa09Eb252N2c2SjcrQUFBQUIzTnphQzF5YzIKRUFBQUdCQU1PQ2V3eE1tQncva3pTbGNVdCtITXk1dkg5aGo5ZTNka04zVHpOSzY2T3lYdGFZM0tiM3VQdTNHMzdlSGhOSAp3cnNkWUJnMk8zTnowSk5MSDlndlpyTDI4R014a2tFMXhXakFrcXVXakp1TUwyN05jSDVXbHdGZFptcjB3MExNdkdaQ3hJCmdVVXNhblJqWkV4QjN2RFNONXFDTkFuOStxdHNSV2xiNFRrK3U2QzNiR3FqTDBvY0lIdlV4TlJZOElETG5jbDJ3N3pkV0sKWUU0eGg2d2VCNElFTTVLYWdkbjNTbUFnZTNZQTMwRGQ1aW5XWmtzNk02M0pPS2pXVHJHWXpSMTZLdWlSZE1CWEZqZkloYwpjT3lNL1phcXpVSk5TT0grWG1tUjViamhGUkhnMDN3NU5Ma1BxZGtNLzE3M1IwODFDYU1IUWM0cUtDK2I0aFF6Y3JlalBVCmN6YWxyZm9mMFJNUVA2MHY1QWFTM0FSZWlLczBhTStvZU1ZRGo4WVhhenZBRnNOK2pqdU0vN0toS0psR0xtNFlMVGYvWWMKdnY5SUZpRkYwL0lOK0lDR1JNSXJJZWhOQXBkeWtYQThVdnpNZExHVXhFem13eGV2ekRJNGdTR3RFQzFWSHo5d0p2Q3NEcQpXNWhMNjljcXdYN255NDJ1WXdxTlVBS3BDZEJISXdBQUFBTUJBQUVBQUFHQkFLSWhkb0ZBazNQNWxNMjMxVGhSb1BoMW5zCmZUMUVHRHR1TkQ4YjRMaDFYOCtZRGt5emI3ZjcvZW5VS2NXRHlNNmdQWjNISzNwcDJia1lCVWNGZ0xGeE9hak1iMXVOK3oKQTc1VzFFclBVbE03OGFubFhFQ285aGovcDR0UzV3cGlWbXBIUEV2TTdzZ210NmNSWjhHYkdENHZDU3dTejRIZ1JDaVYxUwpBSGhFZWJ4UjMrcWU0UHlJVHJmaVBrZ0thWWVsVTNoYXNQL1NYMDF1Q0JXbzExYWF4OFozaFFBUmNNWi9WSGVwcmxKajdZCnhhSTBWaWhVWDc3aWU4WW4wcUtjbnlqSHdaYmxkc0w4S3BjQVRUV29KM25SN2h4dyszbHA3V3JITzVvMm03NHZLd0xTK3kKeWJtZ3F3WXUvaFZSY0Rlb3hzQlNidEdnUkZmbkFZRU1OVk8rc01RUmtMTy9oRHQ1RVVmRXc3ZmNwbzA2QkR1ZVJkd3ZyRgpybEpNSitRaXJVSko3ZXByQ3IwM3RROVpjaTliVWYwN1prTzQrTEJ2TU5keHVNTExtN2I5aE1iNS9sRnZxZFNrdE8rTUV1CjJETjZTVlZnb2xrS1pkQXNpTG9YZ254K1RMOGhPYWFLdVBsYXR4UlAxV252S3hkSEFTSjN6dmkxbkc5WE5rUE9iZ0lRQUEKQU1BS2xHRXY3UGpQK3lHaFdCQnQxWWhic1Y3ZXphalo4Z05vQXBtVHVWb3ZGT3o2czZHRkxKM25FdFZqZ2RLN3pCeStDbgplM0YvTlFKVDcrUkYxdy9OVUJBSFdNOWZhL1RUZVoybitwcjVTMmtBRzNuSUdWU2xPWFRpVDZhVVBJV0VtMk1weUk3UEFFCmY1bHRibVNBZ2U5Zk11MnN4QWlZY3JGZGNmSUxTaHh2dUhvMXNtUi9VdWJCMlEyd2YrSkRSQWRabnNWQWVRUUpRQ3V1QXQKbEZOWEdMblkwaklJbldRajVRbXF4VFFhMVEzTjFyWm9ldkpXcVViTlVzSHMrWDlPd0FBQURCQU85YzZXeGdhVHl1S1N6WgpTWVJzbE56T2FLdnVVRitjZzVJb1JyQS82ZUZYOTFPclhWeG03aUVyUTJUT2hNSHVjWVNwUjlienprMGFRSmFoTVE3eUo3CkU5V3JDMTlscjZHNWxlNTVNREZKcmR5Z2gvazNsNHpvYm4yOW9acEsxbEVBQzZGZC9MUGpIMUtHYlRCWlNQSVR0N0VlZnMKY1A0akgxbGlCSnM4S2JnbjVFTmc3T3lPYkNyeWhhdmUrWWtqcTk0cG01MzBEdWQ4c3lLbE9LWTNMYWQyZmg2bWtkWXVTeApXbXU1VGxnci94UzRwYjB4VmVqY1h6blJpK2pTZTBad0FBQU1FQTBSbEU0Z2paSVVGc0JRK3BJdVhsTHJVZzM2V1AweHR4CndzRTJYa1ZLY1FBaXh3eG1OMk9GZThZVlJQK2pRZzYrS2xnS01jcHZGanhXc3lSWXBXcWlWeVFNZFYrRXFGeSs3aGgxR0oKTVNsUFU4SldhV2Z3cVNGZW93N0FQZkprbkhmVS9TMjZHNllMNFk4Y21SNWFnM2lEUkxKOVVCcmViblFDU2MrUWJ5c2VsZApldHJ4bGo0UVRCQTNiWUFVRC9lSGdQaGR5TjF4ald3SE1LQTNVc2tWVDVjTVJReDhITklNZ21iZ0l6bXBGdGlCbkdta3RHCnZCUUlVTlhHT2kvSUhsQUFBQUZXZDNNVEJBYnpNMk5TNW5aSE5vYVhabExtTnZiUUVDQXdRRgotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
metadata:
  namespace: cicd
  name: flux-git-deploy
type: Opaque

---
apiVersion: v1
data:
  known_hosts: |
    # bitbucket-ssh.ship.gov.sg
    |1|3cCuIm9QlK3HWv6EG1yy5u1ACSE=|p2hHCi3znuzKvIyifcyzAddfWvQ= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCoxa7Dsu2pO5tikmWEsg5aIEyOOUjBzVPXibrhr1FCwtvkLT876g20nEL/CZwro4qZN9yc2MmtRdhjagzZgZXzOLYN4+wP15VCnYdlsV+LuM5Km0x796XZXBrVtnQj/nmcKbeNefFqj++Y7zVrq1J/shNljvxY/yVMF0GMafl7+KguDjuq647ECwswFX4Q+UVHh7Pvy9DxjKU2sclgV2hphAnaDkCOveDkzscRv9YfYV/1B4Db9P3yYnUjD6oyO7Gvx2eBqhZSWkJYUZBHikW5hqptJTkwnH/odG6hsvGPRolXI6/kF/vIs5vwgDfJfPHmfJUDJmhJBjXDiKXDkYox
kind: ConfigMap
metadata:
  name: flux-ssh-config
  namespace: cicd
---
apiVersion: v1
data:
  ca.cer: |-
    -----BEGIN CERTIFICATE-----
    MIIFhDCCBGygAwIBAgITGAAAADagRrZB4Cu+rwAEAAAANjANBgkqhkiG9w0BAQsF
    ADBvMRIwEAYKCZImiZPyLGQBGRYCc2cxEzARBgoJkiaJk/IsZAEZFgNnb3YxFjAU
    BgoJkiaJk/IsZAEZFgZuZWN0YXIxETAPBgoJkiaJk/IsZAEZFgFpMRkwFwYDVQQD
    ExBpLUlXSU5TVlJEQzAxLUNBMB4XDTIxMDEyMTAzMzExN1oXDTI2MDEyMDAzMzEx
    N1owMjEwMC4GA1UEAxMnRU5QLUNBLU1HTVQgUk9USyBJbnRlcm1lZGlhdGUgQXV0
    aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1YPmlqfxi5mX
    NitUjO0iaQX05qk7wA2VNCSyKP0w3kHnkqtkxsjzgHQTezG19el6sGFhtblm870w
    9Db1UVkIq8G3LzspqmDHeLPm1ulUWO389pgXXquqVAAH1kbIUVyzXPb+4mhtmqLm
    4TNW7K0uvMfRDic7Oq6fQM5amAAgneo5x7FP5lIyfAQhe7tyD2KlJZEltCP3oQJE
    LGMO7SZxd6V1vWtFKofDM0XA4QmTEZsokXrBHcA3Q5WkVw+oNq2jqe0pN+ha6Uva
    UHp67CJ3pZm/8yjca33z4zQu6Bh1o+nkwNEyTT3yRwhf9hZnYpqkzu1jiQF9mbYH
    qAcuCMbP8wIDAQABo4ICVDCCAlAwPAYJKwYBBAGCNxUHBC8wLQYlKwYBBAGCNxUI
    h5f6YIepug/llwSFn+p0h+mUUm+Cn5sBg6XoCQIBZAIBETAOBgNVHQ8BAf8EBAMC
    AYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQULlz3M5G3YZj40gceCkwlDKHJ
    yEUwHwYDVR0jBBgwFoAUOKCC7d0uTFYVCLv3ZogW3RS1NGIwgd8GA1UdHwSB1zCB
    1DCB0aCBzqCBy4aByGxkYXA6Ly8vQ049aS1JV0lOU1ZSREMwMS1DQSgzKSxDTj1J
    V0lOU1ZSREMwNSxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049
    U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1pLERDPW5lY3RhcixEQz1nb3Ys
    REM9c2c/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNz
    PWNSTERpc3RyaWJ1dGlvblBvaW50MIHMBggrBgEFBQcBAQSBvzCBvDCBuQYIKwYB
    BQUHMAKGgaxsZGFwOi8vL0NOPWktSVdJTlNWUkRDMDEtQ0EsQ049QUlBLENOPVB1
    YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRp
    b24sREM9aSxEQz1uZWN0YXIsREM9Z292LERDPXNnP2NBQ2VydGlmaWNhdGU/YmFz
    ZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MA0GCSqGSIb3DQEB
    CwUAA4IBAQCREeWP107QkUXserCmxE4/x+SAg17HPhX2bCvt7ljevEn1IQcZIxoj
    Yfl6eDE4I9mPG+RqdWwfGyVsd+PE3KQPCZ/G4yssQhaWJft/hsE16/DW0V8kC1Qz
    zg7gr97yv32KB0ql/SA0n1HFqpYqMkL81+aBQsTiGgPEXvdkYOHD+aiXNpUhSGHW
    wktpREQwugzIJ6ZdtCltDjs+YBiDMmXVNsoYSGT76umjXwjMT3Zv3/C5cy3XS0NX
    l4MjpcEIvZsZoh7zItqBRW4BIWwQZ5diJUIJhYuy+8Hm90GA91x7k1InRaIDd6m8
    S3BMlphLccXD6RB0LIUt2EIZPE2w0+39
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: nexus-ca
  namespace: cicd
